### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by deen13** [deen13/IPLary#8]
# Commands for version 0.1

- [x] `<ESC>C	`		        start advanced mode
- [x] `c`					barcode select 
- [x] `b` 					barcode itself
- [x] `<DEL>` clear current field 
- [x] `W`					box field create 
- [ ] `<CAN>`				clear all data 
- [ ] `D`					delete field 
- [ ] `<ESC>I`			        field increment
- [ ] `<ESC>D`			        field decrement
- [x] `H`					human readable field 
- [x] `L`					line field 
- [ ] `<DLE>` reset                          
- [ ] `x`					text box create 
- [ ] `w` 					width of line, box, bar or char 
- [ ] `<GS>`			increment id
 
# Commands for later versions

**Comment by deen13** [comment]
@Inominie Can you check the time for completeness?
